const DEFAULT_AVATAR='https://ts1.tc.mm.bing.net/th/id/R-C.5c5224bd34a0aee8c411509e0d154575?rik=4fXwdrQ3mRIlvw&riu=http%3a%2f%2fbpic.588ku.com%2felement_pic%2f01%2f55%2f09%2f4557474d965eb71.jpg&ehk=wlOkaUqmQA0OH26%2bPRQ4JBO3sk6Wv8ID%2flpRkImF23Y%3d&risl=&pid=ImgRaw&r=0';
const DEFAULT_BIO='\u8fd9\u4e2a\u4eba\u8fd8\u6ca1\u6709\u7b80\u4ecb\u54e6~';
function checkAuth(){var u=JSON.parse(localStorage.getItem('currentUser')||'null');if(!u){window.location.href='login.html';return null}return u}
function logout(){if(confirm('确定要退出登录吗？')){localStorage.removeItem('currentUser');window.location.href='index.html'}}
function loadNav(){var u=JSON.parse(localStorage.getItem('currentUser')||'null'),l=document.getElementById('navLinks');if(u){var a=u.avatar||DEFAULT_AVATAR;l.innerHTML='<a href="index.html">首页</a><a href="dashboard.html">后台管理</a><span style="color:rgba(255,255,255,.8)"><img src="'+a+'" alt="" style="width:24px;height:24px;border-radius:50%;vertical-align:middle;margin-right:4px;object-fit:cover">欢迎, '+u.username+'</span><a href="profile.html" style="color:rgba(255,255,255,.8);text-decoration:none">个人资料</a><a href="javascript:logout()">退出</a>'}else{l.innerHTML='<a href="index.html">首页</a><a href="login.html">登录</a><a href="register.html">注册</a>'}}
function loadProfile(){var u=checkAuth();if(!u)return;loadNav();document.getElementById('username').value=u.username;document.getElementById('bio').value=u.bio||DEFAULT_BIO;var a=u.avatar||DEFAULT_AVATAR;document.getElementById('avatarImg').src=a}
var cropState={img:null,scale:1,zoom:1,offsetX:0,offsetY:0,dragStartX:0,dragStartY:0,dragging:false},CROP_SIZE=260;
function getDisplayScale(){return cropState.scale*cropState.zoom}
function renderCropImage(){var img=cropState.img;if(!img)return;var ds=getDisplayScale(),dw=img.naturalWidth*ds,dh=img.naturalHeight*ds,ci=document.getElementById('cropImage');ci.style.width=dw+'px';ci.style.height=dh+'px';ci.style.left=cropState.offsetX+'px';ci.style.top=cropState.offsetY+'px'}
function clampOffset(oX,oY,dW,dH){if(dW<=CROP_SIZE){oX=(CROP_SIZE-dW)/2}else{oX=Math.min(0,Math.max(oX,CROP_SIZE-dW))}if(dH<=CROP_SIZE){oY=(CROP_SIZE-dH)/2}else{oY=Math.min(0,Math.max(oY,CROP_SIZE-dH))}return{x:oX,y:oY}}
function uploadAvatar(i){var f=i.files[0];if(!f)return;var r=new FileReader();r.onload=function(e){var img=new Image();img.onload=function(){cropState.img=img;var sx=CROP_SIZE/img.naturalWidth,sy=CROP_SIZE/img.naturalHeight;cropState.scale=Math.max(sx,sy);cropState.zoom=1;var ds=getDisplayScale(),dw=img.naturalWidth*ds,dh=img.naturalHeight*ds;cropState.offsetX=(CROP_SIZE-dw)/2;cropState.offsetY=(CROP_SIZE-dh)/2;document.getElementById('cropImage').src=e.target.result;renderCropImage();document.getElementById('cropModal').style.display='flex'};img.src=e.target.result};r.readAsDataURL(f);i.value=''}
function confirmCrop(){var img=cropState.img;if(!img)return;var ds=getDisplayScale(),cx=-cropState.offsetX/ds,cy=-cropState.offsetY/ds,cs=CROP_SIZE/ds,canvas=document.createElement('canvas'),AS=200;canvas.width=AS;canvas.height=AS;var ctx=canvas.getContext('2d');ctx.beginPath();ctx.arc(AS/2,AS/2,AS/2,0,Math.PI*2);ctx.closePath();ctx.clip();ctx.drawImage(img,cx,cy,cs,cs,0,0,AS,AS);var d=canvas.toDataURL('image/jpeg',0.7);document.getElementById('avatarImg').src=d;document.getElementById('avatarInput').dataset.preview=d;document.getElementById('cropModal').style.display='none';cropState.img=null}
function cancelCrop(){document.getElementById('cropModal').style.display='none';document.getElementById('cropImage').src='';cropState.img=null}
(function(){var cc=document.getElementById('cropContainer');cc.addEventListener('mousedown',function(e){cropState.dragging=true;cropState.dragStartX=e.clientX-cropState.offsetX;cropState.dragStartY=e.clientY-cropState.offsetY});document.addEventListener('mousemove',function(e){if(!cropState.dragging||!cropState.img)return;var ds=getDisplayScale(),dw=cropState.img.naturalWidth*ds,dh=cropState.img.naturalHeight*ds,nx=e.clientX-cropState.dragStartX,ny=e.clientY-cropState.dragStartY,co=clampOffset(nx,ny,dw,dh);cropState.offsetX=co.x;cropState.offsetY=co.y;renderCropImage()});document.addEventListener('mouseup',function(){cropState.dragging=false});cc.addEventListener('touchstart',function(e){var t=e.touches[0];cropState.dragging=true;cropState.dragStartX=t.clientX-cropState.offsetX;cropState.dragStartY=t.clientY-cropState.offsetY;e.preventDefault()});document.addEventListener('touchmove',function(e){if(!cropState.dragging||!cropState.img)return;var t=e.touches[0],ds=getDisplayScale(),dw=cropState.img.naturalWidth*ds,dh=cropState.img.naturalHeight*ds,nx=t.clientX-cropState.dragStartX,ny=t.clientY-cropState.dragStartY,co=clampOffset(nx,ny,dw,dh);cropState.offsetX=co.x;cropState.offsetY=co.y;renderCropImage();e.preventDefault()});document.addEventListener('touchend',function(){cropState.dragging=false});cc.addEventListener('wheel',function(e){e.preventDefault();if(!cropState.img)return;var oz=cropState.zoom,dt=e.deltaY>0?-0.1:0.1;cropState.zoom=Math.max(0.5,Math.min(3,oz+dt));var rect=cc.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top,os=oz*cropState.scale,ns=cropState.zoom*cropState.scale,ow=cropState.img.naturalWidth*os,oh=cropState.img.naturalHeight*os,rx=(mx-cropState.offsetX)/ow,ry=(my-cropState.offsetY)/oh,nw=cropState.img.naturalWidth*ns,nh=cropState.img.naturalHeight*ns,co=clampOffset(mx-rx*nw,my-ry*nh,nw,nh);cropState.offsetX=co.x;cropState.offsetY=co.y;renderCropImage()},{passive:false})})();
async function handleSave(e){e.preventDefault();var u=checkAuth();if(!u)return;var username=document.getElementById('username').value.trim(),bio=document.getElementById('bio').value.trim(),avatarInput=document.getElementById('avatarInput'),newAvatar=avatarInput.dataset.preview||u.avatar||DEFAULT_AVATAR;if(!username){document.getElementById('error').textContent='用户名不能为空';document.getElementById('error').style.display='block';document.getElementById('success').style.display='none';return}var user=JSON.parse(localStorage.getItem('currentUser'));try{var res=await fetch('https://mynewswork.3454381311.workers.dev/api/users/'+user.id,{method:'PUT',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(user?user.token:'')},body:JSON.stringify({username:username,bio:bio,avatar:newAvatar})});if(res.ok){var updated=await res.json();var currentToken=user.token;localStorage.setItem('currentUser',JSON.stringify({id:updated.id,username:updated.username,token:currentToken,avatar:updated.avatar||'',bio:updated.bio||''}));document.getElementById('error').style.display='none';document.getElementById('success').textContent='保存成功！';document.getElementById('success').style.display='block';setTimeout(function(){document.getElementById('success').style.display='none'},2000);loadNav();document.getElementById('oldPassword').value='';document.getElementById('newPassword').value='';document.getElementById('confirmPassword').value='';delete avatarInput.dataset.preview}else{var d=await res.json();alert(d.error||'保存失败')}}catch(err){alert('保存失败: '+err.message)}}
loadProfile();